-- Run this in the Supabase SQL editor to create the newsletter subscriptions table

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  verified boolean not null default false,
  token text not null,
  created_at timestamptz not null default now(),
  verified_at timestamptz
);

create index if not exists newsletter_token_idx on public.newsletter_subscribers (token);
create index if not exists newsletter_email_idx on public.newsletter_subscribers (email);
