-- Run this in the Supabase SQL editor to create the waitlist table

create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text not null,
  product text not null default 'hoodie',
  unique (email, product)
);

create index if not exists waitlist_product_idx on public.waitlist (product);
create index if not exists waitlist_email_idx on public.waitlist (email);
