-- Run this in Supabase SQL editor for the same project used by Vercel.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  email text,
  stripe_checkout_session_id text not null unique,
  stripe_customer_id text,
  amount_total bigint,
  currency text,
  items text,
  payment_status text
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);

-- Allows the app to request a PostgREST schema refresh after migrations.
create or replace function public.reload_schema_cache()
returns void
language sql
security definer
set search_path = public
as $$
  select pg_notify('pgrst', 'reload schema');
$$;

grant execute on function public.reload_schema_cache() to anon, authenticated, service_role;
