-- Run this in Supabase SQL editor to set up the inventory table

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  product_id text not null unique,
  stock integer not null default 0
);

create index if not exists inventory_product_id_idx on public.inventory (product_id);

-- Insert initial inventory for rashguard and shorts
insert into public.inventory (product_id, stock) values ('rashguard', 9), ('shorts', 9)
on conflict (product_id) do nothing;

-- Create a function to reduce inventory
create or replace function public.reduce_inventory(
  p_product_id text,
  p_quantity integer default 1
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current_stock integer;
  v_new_stock integer;
begin
  -- Get current stock with row lock
  select stock into v_current_stock
  from inventory
  where product_id = p_product_id
  for update;

  if v_current_stock is null then
    return jsonb_build_object(
      'ok', false,
      'message', 'Product not found in inventory'
    );
  end if;

  if v_current_stock < p_quantity then
    return jsonb_build_object(
      'ok', false,
      'message', 'Insufficient stock',
      'current_stock', v_current_stock,
      'requested_quantity', p_quantity
    );
  end if;

  v_new_stock := v_current_stock - p_quantity;

  update inventory
  set stock = v_new_stock, updated_at = now()
  where product_id = p_product_id;

  return jsonb_build_object(
    'ok', true,
    'previous_stock', v_current_stock,
    'new_stock', v_new_stock
  );
end;
$$;

grant execute on function public.reduce_inventory(text, integer) to anon, authenticated, service_role;

-- Create a function to get current stock
create or replace function public.get_inventory(p_product_id text)
returns table(product_id text, stock integer, updated_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  select inventory.product_id, inventory.stock, inventory.updated_at
  from inventory
  where inventory.product_id = p_product_id;
end;
$$;

grant execute on function public.get_inventory(text) to anon, authenticated, service_role;

-- Create a function to get all inventory
create or replace function public.get_all_inventory()
returns table(product_id text, stock integer, updated_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  select inventory.product_id, inventory.stock, inventory.updated_at
  from inventory
  order by inventory.product_id;
end;
$$;

grant execute on function public.get_all_inventory() to anon, authenticated, service_role;
